### ISSUE TITLE
配置lint and test 的 github actions

### ISSUE THREAD

**Issue by jianan1104** [Fingerstyle-Taiwan/nextjs-frontend#12]
配置lint and test 的 github actions

**Comment by SidStraw** [comment]
lint 看起來已經裝 ESLint 了
test 使用 Jest + Testing Library ?

這個 issue 的範圍應該先聚焦在完成設置跟 GitHub Actions，細節的 Lint 規則另外處理？

**Comment by jianan1104** [comment]
> lint 看起來已經裝 ESLint 了 test 使用 Jest + Testing Library ?
> 
> 這個 issue 的範圍應該先聚焦在完成設置跟 GitHub Actions，細節的 Lint 規則另外處理？

先聚焦在 github actions 流程建立，詳細的lint可後續處理。
