### ISSUE TITLE
配置 prettier action

### ISSUE THREAD

**Issue by Dannyisadog** [Fingerstyle-Taiwan/nextjs-frontend#14]
### 開始日期

2022/10/3

## 目標

讓開發者和 CI/CD 流程能使用以下指令來檢查專案程式碼的格式
```sh
make prettier
```

讓開發者能使用以下指令來格式化專案程式碼
```sh
make prettier-fix
```

### 基本範例

format check
```sh
make prettier
```
format fix
```sh
make prettier-fix
```

### 缺點

使用 prettier 來格式化程式碼，可能會大幅改動整個專案的格式

## 問題

目前 Makefile 還無法透過 make 的方式進入container 執行，在完成此次任務之前需要先加入此功能

**Comment by jianan1104** [comment]
@Dannyisadog Try this?
```console
# ./Makefile
prettier:
    @docker-compose run --rm ContainerAppName sh -c "prettier-commands"
```

**Comment by Dannyisadog** [comment]
這樣是可以，但我希望可以在 Makefile 中多一個 function 來完成這件事，呼叫的時候帶command 當參數
