### ISSUE TITLE
💡 [REQUEST] - 徵求coming soon 頁面實作

### ISSUE THREAD

**Issue by jianan1104** [Fingerstyle-Taiwan/nextjs-frontend#30]
### 開始日期

10/18/2022

### 摘要

目前指彈台灣的平台各項功能正在積極準備中，希望建立一個頁面來讓人們知道未來有什麼功能作為一個暫時的入口頁面。

[Figma設計稿](https://www.figma.com/file/zx2y1bsqFZan08npKD8qug/Coming-Soon?node-id=1%3A458)
[html/css參考](https://drive.google.com/drive/folders/14CvHzlQVVbq8JVOs3W-MvkgxDDTHLt8l?usp=sharing) -> 這是用 alpine.js做的

### 基本範例

![image](https://user-images.githubusercontent.com/76777822/196442576-6e204084-c18f-4742-a1ac-c7391c85dd65.png)
![image](https://user-images.githubusercontent.com/76777822/196442643-e8b1e9e3-4d85-415b-960f-fe203cd2f6a4.png)

**Comment by Dannyisadog** [comment]
Finish
